#!/usr/bin/env python3
"""Builds app/src/main/assets/book_morph_ru.tsv.gz: the small part of the OpenCorpora dictionary (via pymorphy3)
that on-device book preparation needs instead of a full morphological analyser.

Lines (tab-separated):
  n  form  lemma:case:gender[|…]      first names, singular forms (Name)
  t  form  lemma:case:gender:number[|…]  forms of the titles in TITLES
  p  noun  gender                      animate nouns, nominative singular («лакей», «старуха»)
  f  word  POS                         function words: INTJ PRCL CONJ PREP NPRO
  a  word  ADVB|PRED                   adverbs and predicatives
  g  form                              geographical names that are never a person's name

Usage: pip install pymorphy3 pymorphy3-dicts-ru; python build_book_morph.py OUT.tsv.gz
"""
import gzip
import sys

import pymorphy3

TITLES = {
    "князь", "княгиня", "княжна", "граф", "графиня", "барон", "баронесса", "генерал", "генеральша",
    "полковник", "капитан", "поручик", "подпоручик", "майор", "господин", "госпожа", "мадам", "мадемуазель",
    "мсье", "сударь", "сударыня", "барыня", "барин", "доктор", "профессор", "чиновник", "купец", "купчиха",
    "леди", "лорд", "сэр", "мистер", "миссис", "мисс", "фрау", "герр", "сеньор", "сеньора", "синьор", "синьора",
    "пан", "пани", "месье", "миледи", "милорд",
}
GENDER = {"masc": "m", "femn": "f", "neut": "n", None: "", "ms-f": "c"}


def main(out: str) -> None:
    m = pymorphy3.MorphAnalyzer()
    names, titles, people, function, adverbs, geo, personal = {}, {}, {}, {}, {}, set(), set()
    for word, tag, normal, *_ in m.dictionary.iter_known_words():
        g = tag.grammemes
        if "-" in word and not word.replace("-", "").isalpha():
            continue
        word, normal = word.replace("ё", "е"), normal.replace("ё", "е")
        if "Name" in g and ("sing" in g or "Sgtm" in g):
            names.setdefault(word, set()).add(f"{normal}:{tag.case}:{GENDER.get(tag.gender, '')}")
        if tag.POS == "NOUN" and "anim" in g and "sing" in g and tag.case == "nomn" and not ({"Name", "Surn", "Patr"} & g):
            people.setdefault(word, set()).add(GENDER.get(tag.gender, ""))
        if tag.POS in ("INTJ", "PRCL", "CONJ", "PREP", "NPRO"):
            function.setdefault(word, set()).add(tag.POS)
        if tag.POS in ("ADVB", "PRED"):
            adverbs.setdefault(word, set()).add(tag.POS)
        if "Geox" in g and not ({"Name", "Surn", "Patr"} & g):
            geo.add(word)
        if {"Name", "Surn", "Patr"} & g:
            personal.add(word)
    for title in sorted(TITLES):
        for p in m.parse(title):
            if p.normal_form != title:
                continue
            for x in p.lexeme:
                titles.setdefault(x.word.replace("ё", "е"), set()).add(
                    f"{title}:{x.tag.case}:{GENDER.get(x.tag.gender, '')}:{x.tag.number or 'sing'}")
    rows = ["# Generated by tools/characters/build_book_morph.py from OpenCorpora (CC BY-SA 3.0) via pymorphy3"]
    rows += [f"n\t{w}\t{'|'.join(sorted(v))}" for w, v in sorted(names.items())]
    rows += [f"t\t{w}\t{'|'.join(sorted(v))}" for w, v in sorted(titles.items())]
    rows += [f"p\t{w}\t{''.join(sorted(v))}" for w, v in sorted(people.items())]
    rows += [f"f\t{w}\t{','.join(sorted(v))}" for w, v in sorted(function.items())]
    rows += [f"a\t{w}\t{','.join(sorted(v))}" for w, v in sorted(adverbs.items())]
    # A town that is also a surname («Мышкин», «Пушкина») is not listed: the book decides.
    rows += [f"g\t{w}" for w in sorted(geo - personal)]
    with gzip.open(out, "wt", encoding="utf-8", compresslevel=9) as f:
        f.write("\n".join(rows) + "\n")
    print(out, len(rows), "lines")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "book_morph_ru.tsv.gz")
