package com.brahmadeo.supertonic.tts.books.prepare

/** The part of a Russian dictionary that character extraction needs (assets/book_morph_ru.tsv.gz, generated by
 * tools/characters/build_book_morph.py from OpenCorpora): forms of first names with case and gender, forms of
 * titles, animate nouns, function words, adverbs and geographical names. Everything else is decided by the
 * book's own statistics. Keys are lowercase with «е» for «ё». */
class BookMorph private constructor(
    private val names: Map<String, List<Parse>>,
    private val titles: Map<String, List<Parse>>,
    private val people: Map<String, String>,
    private val function: Map<String, String>,
    private val adverbs: Set<String>,
    private val geo: Set<String>,
) {
    /** Every form of a first name (by its nominative): to see which forms of the lexeme the book itself uses. */
    private val lexemes: Map<String, Set<String>> by lazy {
        val out = HashMap<String, MutableSet<String>>()
        for ((form, parses) in names) for (p in parses) out.getOrPut(p.lemma) { HashSet() } += form
        out
    }
    /** [gender]: m / f / n / c (common) / "" (unknown); [number]: sing / plur. */
    data class Parse(val lemma: String, val case: String, val gender: String, val number: String = "sing")

    fun name(word: String): List<Parse> = names[key(word)].orEmpty()
    fun title(word: String): List<Parse> = titles[key(word)].orEmpty()
    /** Gender of an animate noun in the nominative singular («лакей» → m), or null. */
    fun person(word: String): String? = people[key(word)]
    /** INTJ / PRCL / CONJ / PREP / NPRO (comma-separated when several), or null. */
    fun function(word: String): String? = function[key(word)]
    fun lexeme(lemma: String): Set<String> = lexemes[lemma].orEmpty()
    fun adverb(word: String) = key(word) in adverbs
    fun geo(word: String) = key(word) in geo

    companion object {
        fun key(w: String) = w.lowercase().replace('ё', 'е')
        val EMPTY = BookMorph(emptyMap(), emptyMap(), emptyMap(), emptyMap(), emptySet(), emptySet())

        fun load(lines: Sequence<String>): BookMorph {
            val names = HashMap<String, List<Parse>>()
            val titles = HashMap<String, List<Parse>>()
            val people = HashMap<String, String>()
            val function = HashMap<String, String>()
            val adverbs = HashSet<String>()
            val geo = HashSet<String>()
            for (line in lines) {
                if (line.isEmpty() || line[0] == '#') continue
                val f = line.split('\t')
                when (f[0]) {
                    "n" -> names[f[1]] = f[2].split('|').map { val p = it.split(':'); Parse(p[0], p[1], p[2]) }
                    "t" -> titles[f[1]] = f[2].split('|').map { val p = it.split(':'); Parse(p[0], p[1], p[2], p[3]) }
                    "p" -> people[f[1]] = f[2]
                    "f" -> function[f[1]] = f[2]
                    "a" -> adverbs += f[1]
                    "g" -> geo += f[1]
                }
            }
            return BookMorph(names, titles, people, function, adverbs, geo)
        }

        fun load(stream: java.io.InputStream): BookMorph =
            java.util.zip.GZIPInputStream(stream).bufferedReader(Charsets.UTF_8).useLines { load(it) }
    }
}
